### PR TITLE
WIP - rework singleton logic

### PR DESCRIPTION
**Pull request by Sinewyk**
Hmm ...

It's a lot easier to reason about if recluster exports a singleton, just like the cluster module. `assert` uses for state conformity.

Tests are fully isolated (you will be happy that I came back to `tap` :stuck_out_tongue_closed_eyes: ), and we have some hooks for some events, `listening` when at least one working is listening, `fully-listening` when all workers are listening, `stopped` when we asked cluster to stop and all workers `exit`-ed.

My objective is to get to where you were before in terms of feature, and get no downtime in case of proper reload (should be working if cluster.workers aren't lying about their `state`).

This should be a major version increase in case it is merged.

And as always, I'm fully open to dialogue/help :smile: 

Missing:
  * readyWhen behavior
  * timeout in case worker doesn't want to die.
  * custom logger
  * maybe a `force` option for the stop method to process.exit() instead of disconnect.

There's still some Error: channel closed sometimes, I still don't quite know if it's my fault or because cluster module is still unstable.

### CODE REVIEW

**Comment by spion** [comment]
Why not publish this as a completely different module? :D The changes are too big to introduce to recluster without risking breakage and stability, and I'm not sure if I'll be able to find the time to throughly review them.

(And by too big, I do mean that every single line has been replaced, lol)

**Comment by Sinewyk** [comment]
Haha, yeah, it's a rewrite.

I do strongly advise you to at least try to export a singleton instead of exporting a kinda class. It makes everything easier imo.

Steal away bro ^^. I'll probably just use this internally then.

Cya =).

**Comment by Sinewyk** [comment]
Oh yeah. I forgot also, when using the reloading, you should try to spawn new workers maybe before shutting down the old ones. Like ... to ensure 0 downtime maybe ?

It's what I tried to implement and it 'seems' to be working https://github.com/doxout/recluster/pull/30/files#diff-168726dbe96b3ce427e7fedce31bb0bcR167, if we believe the unit tests https://github.com/doxout/recluster/pull/30/files#diff-03cedc2df2fa9d01239c4790a0e7d0deR89

PS: I don't know what you workflow is ... but seriously ...
`nodemon ./node_modules/.bin/tap test/*.js` is a must for TDD, you just code and immediate feedback.
It's the first time I seriously used TDD, and I like it a lot :stuck_out_tongue:

**Comment by spion** [comment]
recluster does spawn new workers before shutting down old ones. The [`stopOld` function is wrapped by `allReady`](https://github.com/doxout/recluster/blob/master/index.js#L231), which ensures that at least the same number of workers have been spawned and have become ready before shutting down the old ones.

**Comment by Sinewyk** [comment]
Hmm. Weird, in practice it didn't seem to work, I always had a (very small, sub second) downtime.

**Pull request closed without merging**
